# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from client import arg


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(295, 220)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.IP = QtWidgets.QLineEdit(self.centralwidget)
        self.IP.setDisabled(True)
        self.IP.setGeometry(QtCore.QRect(125, 30, 100, 20))
        self.IP.setInputMethodHints(QtCore.Qt.ImhNone)
        self.IP.setObjectName("IP")

        self.port = QtWidgets.QLineEdit(self.centralwidget)
        self.port.setDisabled(True)
        self.port.setGeometry(QtCore.QRect(125, 70, 100, 20))
        self.port.setObjectName("port")

        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setDisabled(False)
        self.name.setGeometry(QtCore.QRect(125, 140, 100, 20))
        self.name.setObjectName("name")

        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(10, 10, 181, 17))
        self.radioButton.setObjectName("custom")
        self.radioButton.toggled.connect(self.on_selected)

        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 110, 82, 17))
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("default")
        # self.radioButton_2.Name("radioButton_2")
        self.radioButton_2.toggled.connect(self.on_selected)

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(134, 180, 131, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.send_data)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(15, 35, 47, 13))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(15, 75, 100, 13))
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(15, 145, 100, 13))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Настройки"))
        self.IP.setText(_translate("MainWindow", "127.0.0.1"))
        self.port.setText(_translate("MainWindow", "7777"))

        self.radioButton.setText(_translate("MainWindow", "Пользовательские данные"))
        self.radioButton_2.setText(_translate("MainWindow", "Стандарт"))

        self.pushButton.setText(_translate("MainWindow", "Подключиться"))

        self.label.setText(_translate("MainWindow", "IP-адрес"))
        self.label_2.setText(_translate("MainWindow", "Порт(1024-65535)"))
        self.label_3.setText(_translate("MainWindow", "Имя в чате"))

    def on_selected(self):
        rb = self.centralwidget.sender()
        if rb.isChecked():
            if rb.objectName() == 'default':
                self.port.setText('7777')
                self.port.setDisabled(True)
                self.IP.setText('127.0.0.1')
                self.IP.setDisabled(True)

            else:
                self.port.setDisabled(False)
                self.IP.setDisabled(False)

    def send_data(self):
        print(arg(self.IP.text(), self.port.text()))
        # print(self.IP.text(), self.port.text())
        # # self.hide( ) закрыть окно
        if (arg(self.IP.text(), self.port.text()))[0] is False:
            msg = QMessageBox()
            msg.setWindowTitle("Ошибка")
            msg.setText((arg(self.IP.text(), self.port.text()))[1])
            msg.setIcon(QMessageBox.Warning)
            msg.exec_()




if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
